NAME= ../../../add-ons/landscape_addon
TYPE= APP
SRCS=  ../../pulsar_addon_src/CFilter.cpp smooth_land_addon.cpp
RSRCS= land.rsrc
LIBS=  root be translation
LIBPATHS= 
SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = ../../pulsar_addon_src/beos_r4/ ../../pulsar_addon_src/ 
OPTIMIZE= SOME
DEFINES= 
WARNINGS = 
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =
APP_VERSION = 
DRIVER_PATH = 
## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
