NAME= ../../../add-ons/balls_addon
TYPE= APP
SRCS=  ../../pulsar_addon_src/CFilter.cpp balls_addon.cpp balls_addon_PutSprite.cpp
RSRCS=  balls_addon.rsrc Ball.rsrc Tennis.rsrc
LIBS=  root be translation
LIBPATHS= 
SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = ../../pulsar_addon_src/beos_r4/ ../../pulsar_addon_src/ 
OPTIMIZE= SOME
DEFINES= 
WARNINGS = 
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =
APP_VERSION = 
DRIVER_PATH = 
## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
