NAME= ../../../add-ons/beatgrid3d_addon
TYPE= APP
SRCS=  ../../pulsar_addon_src/CFilter.cpp \
	Texture_noise.cpp Point3D.cpp Basic_addon_process.cpp Basic_addon.cpp
RSRCS=
LIBS=  root be translation
LIBPATHS= 
SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = ../../pulsar_addon_src/beos_r4/ ../../pulsar_addon_src/ 
OPTIMIZE= SOME
DEFINES= 
WARNINGS = 
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =
APP_VERSION = 
DRIVER_PATH = 
## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
